### ISSUE TITLE
GetAuditLog response is not fully enriched

### ISSUE THREAD

**Issue by AbbanMustafa** [google/go-github#2534]
Many expected fields are omitted from the [AuditEntry](https://github.com/google/go-github/blob/master/github/orgs_audit_log.go#L34) result of the GetAuditLog request.

For example here are 4 logs for different actions

 
```
  actor: ""
  action: "git.clone"
  timestamp:
  org: ""
  transport_protocol_name: ""
  repo: ""
```

```
  actor: ""
  action: "git.fetch"
  timestamp:
  org: ""
  transport_protocol_name: ""
  repo: ""
```

```
  document_id: ""
  actor: ""
  action: "org.sso_response"
  timestamp:
  org: ""
```

```
  document_id: ""
  actor: ""
  action: "pull_request_review_comment.update"
  timestamp:
  org: ""
```

These are very barebones and the AuditEntry has many fields we think are essential that are just not present. Does the request need an additional parameter to ensure we have more verbose logs?
